### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by wuzimi** [Adiii1436/datadoc#1]
Collecting nvidia-cublas-cu12==12.1.3.1
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-win_amd64.whl (439.9 MB)
     ---------------------------------------- 439.9/439.9 MB 1.6 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.1.105
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-win_amd64.whl (10.2 MB)
     ---------------------------------------- 10.2/10.2 MB 2.7 MB/s eta 0:00:00
Collecting nvidia-cuda-nvrtc-cu12==12.1.105
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-win_amd64.whl (19.3 MB)
     ---------------------------------------- 19.3/19.3 MB 2.5 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12==12.1.105
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-win_amd64.whl (821 kB)
     ---------------------------------------- 821.2/821.2 kB 3.5 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement nvidia-cudnn-cu12==8.9.2.26 (from versions: 0.0.1.dev5, 8.9.4.25, 8.9.5.29, 8.9.6.50, 8.9.7.29)
ERROR: No matching distribution found for nvidia-cudnn-cu12==8.9.2.26

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

(myenv) C:\Users\Administrator\Documents\GitHub\datadoc>streamlit run app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.1.19.2:8501

2024-03-21 11:12:42.579 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Administrator\Documents\GitHub\datadoc\app.py", line 3, in <module>
    from main import get_llm_response
  File "C:\Users\Administrator\Documents\GitHub\datadoc\main.py", line 2, in <module>
    from embed_data import chroma_db_store
  File "C:\Users\Administrator\Documents\GitHub\datadoc\embed_data.py", line 4, in <module>
    from langchain_community.document_loaders import DirectoryLoader
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_community\document_loaders\__init__.py", line 190, in <module>
    from langchain_community.document_loaders.sql_database import SQLDatabaseLoader
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_community\document_loaders\sql_database.py", line 10, in <module>
    class SQLDatabaseLoader(BaseLoader):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_community\document_loaders\sql_database.py", line 22, in SQLDatabaseLoader
    query: Union[str, sa.Select],
AttributeError: module 'sqlalchemy' has no attribute 'Select'

Thanks for help in advance!

**Comment by Adiii1436** [comment]
I have fixed some dependencies conflicts can you try again? Also mention which device you are using.

Don't use cached packages from your system. 
1. Clear the cache: `pip cache purge`
2. Install packages: `pip install -r requirements.txt`
3. Or Directly use this: `pip install -r requirements.txt -no-cache-dir`

**Comment by wuzimi** [comment]
Thanks for you quick reply. However I got the same error message as above. I am using win10 PC without Nvidia GPU. It seem your app require this to run? 
Collecting nvidia-cuda-runtime-cu12==12.1.105
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-win_amd64.whl (821 kB)
     ---------------------------------------- 821.2/821.2 kB 5.8 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement nvidia-cudnn-cu12==8.9.2.26 (from versions: 0.0.1.dev5, 8.9.4.25, 8.9.5.29, 8.9.6.50, 8.9.7.29)
ERROR: No matching distribution found for nvidia-cudnn-cu12==8.9.2.26

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

(myenv) C:\Users\Administrator\Documents\GitHub\datadoc>streamlit run app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.1.19.2:8501

2024-03-21 15:15:15.500 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Administrator\Documents\GitHub\datadoc\app.py", line 3, in <module>
    from main import get_llm_response
  File "C:\Users\Administrator\Documents\GitHub\datadoc\main.py", line 2, in <module>
    from embed_data import chroma_db_store
  File "C:\Users\Administrator\Documents\GitHub\datadoc\embed_data.py", line 4, in <module>
    from langchain_community.document_loaders import DirectoryLoader
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_community\document_loaders\__init__.py", line 190, in <module>
    from langchain_community.document_loaders.sql_database import SQLDatabaseLoader
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_community\document_loaders\sql_database.py", line 10, in <module>
    class SQLDatabaseLoader(BaseLoader):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_community\document_loaders\sql_database.py", line 22, in SQLDatabaseLoader
    query: Union[str, sa.Select],
AttributeError: module 'sqlalchemy' has no attribute 'Select'

**Comment by Adiii1436** [comment]
Here is the same issue I found:
https://github.com/langchain-ai/langchain/issues/18528#issuecomment-1978040612

Try using `sqlalchemy==2.0.0` first then try the latest one i.e `sqlalchemy==2.0.28`.

**Comment by wuzimi** [comment]
I followed your instructions and then installed some other dependencies, and finally I can open your app.
But after I asked a question, it run and responded with a new error like this:

OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like sentence-transformers/all-MiniLM-L6-v2 is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
Traceback:
File "C:\Users\Administrator\Documents\GitHub\datadoc\myenv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "C:\Users\Administrator\Documents\GitHub\datadoc\app.py", line 75, in <module>
    output = generate_response(user_input, model,explain_to_kid=explain_kid)
File "C:\Users\Administrator\Documents\GitHub\datadoc\app.py", line 41, in generate_response
    response = get_llm_response(prompt, model, image_path, api_key, explain_to_kid)
File "C:\Users\Administrator\Documents\GitHub\datadoc\main.py", line 11, in get_llm_response
    vectordb = chroma_db_store()
File "C:\Users\Administrator\Documents\GitHub\datadoc\embed_data.py", line 32, in chroma_db_store
    embeddings = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")
File "C:\Users\Administrator\Documents\GitHub\datadoc\myenv\lib\site-packages\langchain_community\embeddings\huggingface.py", line 67, in __init__
    self.client = sentence_transformers.SentenceTransformer(
File "C:\Users\Administrator\Documents\GitHub\datadoc\myenv\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 198, in __init__
    modules = self._load_auto_model(
File "C:\Users\Administrator\Documents\GitHub\datadoc\myenv\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 1063, in _load_auto_model
    transformer_model = Transformer(
File "C:\Users\Administrator\Documents\GitHub\datadoc\myenv\lib\site-packages\sentence_transformers\models\Transformer.py", line 35, in __init__
    config = AutoConfig.from_pretrained(model_name_or_path, **model_args, cache_dir=cache_dir)
File "C:\Users\Administrator\Documents\GitHub\datadoc\myenv\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1138, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
File "C:\Users\Administrator\Documents\GitHub\datadoc\myenv\lib\site-packages\transformers\configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
File "C:\Users\Administrator\Documents\GitHub\datadoc\myenv\lib\site-packages\transformers\configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
File "C:\Users\Administrator\Documents\GitHub\datadoc\myenv\lib\site-packages\transformers\utils\hub.py", line 441, in cached_file
    raise EnvironmentError
    
  ChatGPT gave me the following instruction, but I don't know how to proceeds.
  
  from transformers import AutoModel, AutoConfig

# 指定本地模型文件和配置文件的路径
model_path = '/path/to/your/local/model/file.bin'
config_path = '/path/to/your/local/config/config.json'

# 加载配置文件
config = AutoConfig.from_pretrained(config_path)

# 加载模型
model = AutoModel.from_pretrained(model_path, config=config)

Could you give me any advice? Thanks!

**Comment by Adiii1436** [comment]
> OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like sentence-transformers/all-MiniLM-L6-v2 is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at

You can see it may be internet issue. Sometimes huggingface api takes time to download the models. We are using `embeddings = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")` to create the embeddings. 

Can you try it again? May be by creating whole project again. It doesn't indicate any error in the code itself.

**Comment by wuzimi** [comment]
After installed another dependency pip install chromadb and finally it works. Seem lots of dependencies needs to be included.

**Comment by Adiii1436** [comment]
Chromadb wasn't in the requirements.txt file?

**Comment by wuzimi** [comment]
Yes, at least in my case. By the way I put one pdf file which A Barron magazine pdf and it seems it can't provide any answer.
![Quicker_20240321_175709](https://github.com/Adiii1436/datadoc/assets/120776424/4c40c18c-202a-4c12-b172-c54a5d277c38)

**Comment by Adiii1436** [comment]
Do these things:
1. Delete the existing chromadb folder that was present when you downloaded the repo.
2. Whenever you add the new files in the transcripts folder, make sure to delete chromadb folder before running the file.
3. Try to ask question that is present in the file. Instead of asking "what is present in the file", ask something specific related to any topic that is present in the file.

**Comment by wuzimi** [comment]
Thanks! By the way besides pdf file, does it support other format like txt or word?

**Comment by Adiii1436** [comment]
Yes it supports docx,pdf,txt,md,pptx now. Pull the code to use it.
